# Generated by Django 5.0.3 on 2024-04-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_register', '0001_initial'),
        ('vendors', '0018_companyservicepromotion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company', 'customer_name')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('company', 'supplier_name', 'item_name')},
        ),
    ]
