# Generated by Django 5.0.3 on 2024-04-16 06:18

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_register', '0002_alter_customer_unique_together_and_more'),
        ('vendors', '0020_alter_companydocuments_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_id', models.CharField(db_index=True, max_length=10)),
                ('client', models.CharField(max_length=20)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('work_type', models.CharField(max_length=15)),
                ('project_name', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('nature_of_work', models.CharField(max_length=15)),
                ('building_name', models.CharField(blank=True, max_length=20, null=True)),
                ('villa_number', models.IntegerField(blank=True, null=True)),
                ('quoted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vat_or_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_remarks', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.customer')),
            ],
        ),
    ]
