# Generated by Django 5.0.3 on 2024-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_register', '0004_alter_dailyregister_unique_together_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
