# Generated by Django 5.0.3 on 2024-04-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_register', '0006_customer_email_supplier_email_and_more'),
        ('vendors', '0020_alter_companydocuments_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_purchase', models.CharField(max_length=20)),
                ('vat_or_tax', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
                ('purchase_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.dailyregister')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.supplier')),
            ],
            options={
                'unique_together': {('company', 'supplier', 'item_purchase', 'bill_amount', 'payment_type', 'purchase_against')},
            },
        ),
    ]
