# Generated by Django 5.0.3 on 2024-04-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_register', '0007_purchase'),
        ('vendors', '0020_alter_companydocuments_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_identifier', models.CharField(db_index=True, max_length=10)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_status', models.CharField(default='Pending', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('invoice_date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.dailyregister')),
            ],
            options={
                'unique_together': {('company', 'order_id', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expense_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.dailyregister')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.customer')),
            ],
            options={
                'unique_together': {('to', 'description', 'amount_paid', 'payment_type', 'expense_against')},
            },
        ),
        migrations.CreateModel(
            name='PaymentCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=25, null=True)),
                ('collection_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('differences', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_register.statementofaccounts')),
            ],
            options={
                'unique_together': {('company', 'invoice', 'customer')},
            },
        ),
    ]
