# Generated by Django 5.0.3 on 2024-04-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_register', '0009_alter_expense_unique_together_expense_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
