# Generated by Django 5.0.3 on 2024-05-01 14:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0038_companyprofile_template_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('date_of_birth', models.DateField()),
                ('total_years_of_experience', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NIL', 'Nil')], max_length=3)),
                ('current_location', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1)),
                ('qualification', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('upload_resume', models.FileField(upload_to='resumes/')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
