# Generated by Django 5.0.3 on 2024-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
