# Generated by Django 5.0.3 on 2024-04-03 18:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_picture', models.ImageField(upload_to='company_cover_images')),
                ('company_logo', models.ImageField(upload_to='company_logos')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('tagline', models.CharField(max_length=250, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('average_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('momentum', models.TextField(blank=True)),
                ('recognition', models.TextField(blank=True)),
                ('compliments', models.TextField(blank=True)),
                ('happy_clients', models.PositiveIntegerField(blank=True, null=True)),
                ('awards_won', models.PositiveIntegerField(blank=True, null=True)),
                ('projects', models.PositiveIntegerField(blank=True, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=250)),
                ('facebook_url', models.CharField(blank=True, max_length=250)),
                ('instagram_url', models.CharField(blank=True, max_length=250)),
                ('linkedin_url', models.CharField(blank=True, max_length=250)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_cover_picture', models.ImageField(blank=True, upload_to='company_service_cover_picture')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='vendors.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWorksDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_images', models.ImageField(upload_to='work_done_image')),
                ('work_name', models.CharField(max_length=250)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='vendors.companyprofile')),
            ],
        ),
    ]
