# Generated by Django 5.0.3 on 2024-04-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_companyprofile_company_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservices',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='companyservices',
            name='price',
        ),
        migrations.CreateModel(
            name='CompanySubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_service_cover_picture', models.ImageField(blank=True, upload_to='company_sub_service_cover_picture')),
                ('sub_service_name', models.CharField(max_length=100)),
                ('sub_service_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('company_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyservices')),
            ],
        ),
    ]
