# Generated by Django 5.0.3 on 2024-04-13 08:33

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_businesscards_hrsystememployee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hrsystememployee',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=50)),
                ('job_position', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=20)),
                ('job_nature', models.CharField(max_length=20)),
                ('job_experience', models.IntegerField()),
                ('no_of_vacancy', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('posted_date', models.DateField()),
                ('last_date_to_apply', models.DateField()),
                ('close_date', models.DateField()),
                ('language', models.CharField(max_length=15)),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeadGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('created_on', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('name', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=20)),
                ('lead_source', models.CharField(max_length=15)),
                ('lead_owner', models.CharField(max_length=20)),
                ('lead_status', models.CharField(max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
            ],
        ),
    ]
