# Generated by Django 5.0.3 on 2024-04-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_hrsystememployee_unique_together_jobs_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hrsystememployee',
            unique_together={('company', 'employee_id')},
        ),
    ]
