# Generated by Django 5.0.3 on 2024-04-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_jobscategory_alter_jobs_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgeneration',
            name='lead_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='leadgeneration',
            unique_together={('company', 'lead_id')},
        ),
    ]
