# Generated by Django 5.0.3 on 2024-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_alter_leadgeneration_lead_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgeneration',
            name='lead_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
