# Generated by Django 5.0.3 on 2024-04-13 17:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_alter_leadgeneration_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('ZIP_code', models.CharField(max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('emergency_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_city', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_state', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_ZIPcode', models.CharField(blank=True, max_length=10, null=True)),
                ('business_card_confirmation', models.BooleanField(default=False)),
                ('employee_id', models.CharField(db_index=True, max_length=6)),
                ('username', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('work_status', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('office_location', models.CharField(max_length=50)),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HRA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('documents', models.FileField(blank=True, null=True, upload_to='employee_documents')),
                ('expiry_date', models.DateField()),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_country', models.CharField(blank=True, max_length=50)),
                ('iban_number', models.CharField(blank=True, max_length=30, null=True)),
                ('swift_Code', models.CharField(blank=True, max_length=15, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=15, null=True)),
                ('branch_name', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
            ],
            options={
                'verbose_name': 'HR System Employees',
                'unique_together': {('company', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date', models.DateField(auto_now=True)),
                ('leave', models.IntegerField(blank=True, null=True)),
                ('deduction', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.companyprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.hremployees')),
            ],
            options={
                'verbose_name': 'Employees Payroll',
            },
        ),
        migrations.DeleteModel(
            name='HRSystemEmployee',
        ),
    ]
