# Generated by Django 5.0.3 on 2024-04-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_companydocuments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companydocuments',
            unique_together={('company', 'document_name')},
        ),
    ]
