# Generated by Django 5.0.3 on 2024-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_alter_companydocuments_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyenquiry',
            name='enquiry_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
