# Generated by Django 5.0.3 on 2024-04-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_companyservicepromotion_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hremployees',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
