# Generated by Django 5.0.3 on 2024-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_hremployees_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hremployees',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profile_image'),
        ),
    ]
