# Generated by Django 5.0.3 on 2024-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0026_alter_companyservices_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubservices',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
