# Generated by Django 5.0.3 on 2024-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0027_companysubservices_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubservices',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
