# Generated by Django 5.0.3 on 2024-04-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0028_companysubservices_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubservices',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='approved_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
