# Generated by Django 5.0.3 on 2024-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0029_remove_companysubservices_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscards',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_card_profile_image'),
        ),
    ]
