# Generated by Django 5.0.3 on 2024-04-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0031_payroll_salary_per_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('company', 'employee')},
        ),
    ]
