# Generated by Django 5.0.3 on 2024-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0032_alter_payroll_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgeneration',
            name='lead_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
