# Generated by Django 5.0.3 on 2024-04-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0033_alter_leadgeneration_lead_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadgeneration',
            name='domain',
        ),
    ]
