# Generated by Django 5.0.3 on 2024-04-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0036_qrcodeforbusinesscard_qrcodeforcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocuments',
            name='document_status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
