# Generated by Django 5.0.3 on 2024-04-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0037_companydocuments_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='template_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
